spring:
  application:
    name: securitytool
  datasource:
    url: jdbc:mysql://${DB_HOSTNAME}:${DB_PORT}/${DB_NAME}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none # Disable Hibernate auto DDL to avoid conflict with Flyway
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: maupro2002@gmail.com
    password: ozqt jmlm bfpj vrdx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8081

# Cache settings
spring.cache:
  type: simple

# JWT settings
security:
  jwt:
    expiration-ms: 900000 # 15mins in ms
    refresh-expiration-ms: 7200000 # 2hour in ms

